### ISSUE TITLE
Too Swag

### ISSUE THREAD

**Issue by adiprerepa** [SnootierMoon/SnootierMoon#1]
I am so sorry for this issue, but it had to be addressed.

I think the `README.org` was too swag. I believe section 185.15.1 in the swag bro code indicates that level of swagger (of, or eminating an ABSURD amount of swagger) is dangerous when too high. This repository and especially the `README.org` matches that level.

If this repository is not removed within 72 millenia of the creation, the swag bros of america will have to step in.

Thank you and hot regards,
aditya prerepa

**Comment by adiprerepa** [comment]
+1 this needs to be addressed

**Comment by adiprerepa** [comment]
yep. agreed. +1.

**Comment by adiprerepa** [comment]
oh for sure. +1.

**Comment by aktriv** [comment]
You're right, I am so sorry. Unfortunately, due to certain circumstances, I cannot delete or private this repo. If you have any specific suggestions, please make a pull request. Sorry for any inconveniences.

**Comment by adiprerepa** [comment]
Akshay,

The swag bros organization incorporated will not be pleased with this. However, we have come to the collective decision to conjure a request you must pull.

Have a Snortlastic day,
the swag bros rep #2004 - aditya

**Comment by aktriv** [comment]
closed because cringe and sus

**Comment by adiprerepa** [comment]
> You're right, I am so sorry. Unfortunately, due to certain circumstances, I cannot delete or private this repo. If you have any specific suggestions, please make a pull request. Sorry for any inconveniences.

No one cares about your GitHub, Akshay. Thanks for your time.
